### ISSUE TITLE
No stats from plugin

### ISSUE THREAD

**Issue by toptalo** [wakatime/browser-wakatime#287] opened 2024-10-08 09:18 UTC
Hello!
After update to version 4.0.2 I have not see any stats from plugin in dashboard
Is it work?

**Comment by AxeR21** [comment] 2024-10-08 10:15
I'm encountering the same issue even with 4.0.3.
In Chrome DevTools there's the following error:
`Uncaught (in promise) NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
    at Proxy.n (index.js:125:26)
    at Proxy.r (index.js:228:25)
    at Object.sendHeartbeats (WakaTimeCore.ts:178:49)
    at async background.ts:12:19`

**Comment by alanhamlett** [comment] 2024-10-08 12:21
I've renamed the IndexedDB database and bumped the db version so it's re-created fresh in v4.0.4. Does that fix it?

Duplicate of #286.

**Comment by AxeR21** [comment] 2024-10-08 13:01
Is it normal i see version 4.0.3.2?
Now it seems to work but I had to remove and add extension again to Chrome because evene after upgrading and closing/opening Chrome the issue was still present.
I've noted that in config is still present `queueName: 'heartbeatQueue',`

In console there are a couple more errors:
```
Heartbeat 0 returned status: 202
(anonime) @ WakaTimeCore.ts:232
Heartbeat 1 returned status: 202
(anonime) @ WakaTimeCore.ts:232
Heartbeat 2 returned status: 202
(anonime) @ WakaTimeCore.ts:232
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
at l (browser-polyfill.js:1154:18)
```

**Comment by alanhamlett** [comment] 2024-10-08 13:11
It's v4.0.3.2 because I reverted a rollback and chrome doesn't allow duplicate versions.

Those errors will go away with v4.0.4.

**Comment by AxeR21** [comment] 2024-10-08 13:25
Now I'm on 4.0.4 and it does register stats successfully. There's still the browser-plolyfill error.
Thanks for the amazing support and quick resolution

**Comment by sjclayton** [comment] 2024-10-08 13:55
Stats not being reported for me here on Firefox using 4.0.4, it's been over a week since I've had anything reported from in Firefox, I use [wakapi.dev](wakapi.dev)..

All my other plugins (editors) work with my wakapi instance still... just not the browser extension, nothing changed with my setup other than updating the extension.

**Comment by toptalo** [comment] 2024-10-08 15:45
Updated to 4.0.4 and now looks like all works fine

Thanks!

**Comment by Atko** [comment] 2024-10-08 17:05
@sjclayton that's probably related to the issue #282. I have the same problem under ffox since the plugin version 3.0.24.

**Comment by alanhamlett** [comment] 2024-10-08 18:30
@sjclayton is it working with v4.0.5?

**Comment by sjclayton** [comment] 2024-10-08 20:41
@alanhamlett No it's not... it can't seem to hit the endpoint on my wakapi instance at all now... I keep seeing 404's even trying to retrieve the today's time. 

Seems like you are appending additional duplicate API path's on top of what wakapi is already expecting, and that is making it 404 on everything.  The extension can't get a total daily time, let alone that it still does not appear to be even trying to send heartbeats to the wakapi instance.

**Comment by alanhamlett** [comment] 2024-10-08 20:44
What's your API url setting set to?

**Comment by sjclayton** [comment] 2024-10-08 20:51
This is what was working previously, before the extension was updated.... which I figure things broke sometime around v3.0.22-3.0.24

`https://waka.clayton-tech.ca/api/compat/wakatime/v1`

That is the API url I have set for the extension, it's my self hosted wakapi instance, it's not publicly accessible.

Now any GET requests the extension is trying to send are failing, because it seems to be appending `/api/v1` to the end of the existing url, even though it shouldn't need it. Also like I said I see no POST attempts even with the messed up API path.

**Comment by alanhamlett** [comment] 2024-10-08 21:01
Try with v4.0.6.

**Comment by sjclayton** [comment] 2024-10-08 21:06
The GET requests appear to be returning 200 now... but I still see no daily total time in the extension, and it's still not sending heartbeats to the wakapi server.... so it's back to where it was as of v4.0.4 for what I can see.

**Comment by sjclayton** [comment] 2024-10-08 21:42
@alanhamlett 

Quick question -- has the format for associating sites to a "Project" changed recently...? I have the extension set to only log allowed sites.

The format I use for a site is this, example:

`https://github.com@@code` to log all github.com accesses with the project / tag "code"... this is what has previously worked.

**Comment by alanhamlett** [comment] 2024-10-08 22:19
Yes, we changed the format to remove `@@` and have a structured UI for customizing projects.

**Comment by sjclayton** [comment] 2024-10-08 22:36
@alanhamlett

Ok... I don't actually use Wakatime directly, only Wakapi... so therefore I don't login to the extension... is there any way to do this in the extension without using a Wakatime account?

If not then I won't be able to make use of Wakapi anymore for tracking websites.

**Comment by alanhamlett** [comment] 2024-10-08 22:42
Login happens when you enter your api key, it doesn't mean you need to actually login to any website.

**Comment by sjclayton** [comment] 2024-10-08 22:46
@alanhamlett

Ok, but this *new* structured UI for specifying projects associated to a URL that you mentioned is no where to be found in the extension in Firefox.. is there something I'm missing?

**Comment by alanhamlett** [comment] 2024-10-08 22:51
Here's the `Only track these sites` setting:
<img width="396" alt="Screenshot 2024-10-09 at 12 49 56 AM" src="https://github.com/user-attachments/assets/030f6faf-5288-4ba3-9cef-6d7084fb5dc9">

And the separated out `Custom project names` setting:
<img width="393" alt="Screenshot 2024-10-09 at 12 49 45 AM" src="https://github.com/user-attachments/assets/c8e81642-61ca-4c08-a3f5-6ffde6c7df5c">

**Comment by sjclayton** [comment] 2024-10-08 23:02
Holy shit I'm blind.... Nevermind, I was just in there earlier to grab the API url and looked right at that too, and wondered what it was...

Maybe that's why I asked about the "@@", my brain does weird things like that...

**Comment by alanhamlett** [comment] 2024-10-09 00:01
Closing this because it's most likely due to the `only track allowed sites` setting.

**Closed by alanhamlett** 2024-10-09 00:01 UTC
Labels: bug

**Comment by alanhamlett** [comment] 2024-10-09 06:04
@sjclayton the reason it's not working for you is this:

https://github.com/muety/wakapi/issues/688

**Comment by sjclayton** [comment] 2024-10-09 06:13
@alanhamlett 

Thanks for the prompt replies, I will follow the wakapi issue so I know when things are fixed on their end. 😃

**Comment by rob4226** [comment] 2024-10-11 18:33
I changed this line in the browser extension:
https://github.com/wakatime/browser-wakatime/blob/77d0963d93552756f52e72ed57f0d2f6f7d6239f/src/core/WakaTimeCore.ts#L187

to:

```ts
return { ...heartbeat, userAgent, id: undefined, time: Date.now() / 1000 };
```

to get the browser extension to work in the meantime.

**Comment by alanhamlett** [comment] 2024-10-11 23:02
This is better to not overwrite the heartbeat timestamp:

```typescript
return { ...heartbeat, userAgent, id: undefined, time: Number(heartbeat.time) };
```
